# 19B01A1229  
# Ch.Sri Pallavi
# 11-04-2022#

# **1. Write python program for consider two random array A and B, check if they are equal.**

In [ ]:
import numpy as np
a = np.random.randint(1,10,5)
print("First array:")
print(a)
b = np.random.randint(1,10,5)
print("Second array:")
print(b)
print("Test above two arrays are equal or not!")
result = np.allclose(a, b)
print(result)


First array:
[7 5 5 6 4]
Second array:
[2 4 8 5 4]
Test above two arrays are equal or not!
False


# 2. Write python program for consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [ ]:
import numpy as np

Z = np.ones(10)
print("Ones Array: ",Z)
length=len(Z)
print("Length: ",length)

I = np.random.randint(0,length,20)
print("Random Array: ",I)
I_length=len(I)
print("Length: ",I_length)

Z += np.bincount(I, minlength=len(Z))
print("Result: ",Z)


Ones Array:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Length:  10
Random Array:  [8 7 1 4 0 9 3 4 3 8 4 2 0 9 0 5 3 0 0 7]
Length:  20
Result:  [6. 2. 2. 4. 4. 2. 1. 3. 3. 3.]


# 3. Write python program to get the n largest values of an array.

In [ ]:
import numpy as np
Arr = np.random.randint(0,50,20)
print("Array Elements: ",Arr)
n = int(input("How many largest Numbers you need: "))
print (n," Largest values from Array", Arr[np.argsort(Arr)[-n:]])

Array Elements:  [ 5 41  1 10 17 18 47 22 45 27 38 44  3 15 19 36 21 46 13 31]
How many largest Numbers you need: 5
5  Largest values from Array [41 44 45 46 47]


## 4. Load the energy data from the file Energy Indicators.xls, which is a list of indicators of [energy supply and renewable electricity production] (Energy%20Indicators.xls) from the Dataset (http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of energy.

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
url='http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls'
energy = pd.read_excel(url)

In [ ]:
energy

Unnamed: 0                                         Unnamed: 1  \
0           NaN                                                NaN   
1           NaN                                                NaN   
2           NaN                                                NaN   
3           NaN                                                NaN   
4           NaN                                                NaN   
..          ...                                                ...   
277         NaN                       … denotes no data available.   
278         NaN                                                NaN   
279         NaN                                     Data Quality:    
280         NaN  The data are compiled primarily from the annua...   
281         NaN  For more information, visit http://unstats.un....   

                                            Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0                     Environmental Indicators: Energy        NaN        NaN   
1                                                  NaN        NaN        NaN   
2    Energy Supply and Renewable Electricity Produc...        NaN        NaN   
3                                                  NaN        NaN        NaN   
4                                                  NaN        NaN        NaN   
..                                                 ...        ...        ...   
277                                                NaN        NaN        NaN   
278                                                NaN        NaN        NaN   
279                                                NaN        NaN        NaN   
280                                                NaN        NaN        NaN   
281                                                NaN        NaN        NaN   

                     Unnamed: 5  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4    Last update: December 2015  
..                          ...  
277                         NaN  
278                         NaN  
279                         NaN  
280                         NaN  
281                         NaN  

[282 rows x 6 columns]

In [ ]:
energy = energy.drop(energy.columns[0:2], axis = 1)
energy

Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
45                               Brazil      12149         59   69.64803
46               British Virgin Islands          2         85          0
47                    Brunei Darussalam        127        310   0.045434
48                             Bulgaria        703         97   17.23461
49                         Burkina Faso        164         10   14.50068
..                                  ...        ...        ...        ...
238  Venezuela (Bolivarian Republic of)       2871         95   67.83452
239                            Viet Nam       2554         28   45.32152
240           Wallis and Futuna Islands          0         26          0
241                               Yemen        344         13          0
242                              Zambia        400         26   99.71467

[198 rows x 4 columns]

In [ ]:
energy.head(10)

Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
45                  Brazil      12149         59   69.64803
46  British Virgin Islands          2         85          0
47       Brunei Darussalam        127        310   0.045434
48                Bulgaria        703         97   17.23461
49            Burkina Faso        164         10   14.50068
50                 Burundi         58          6   86.79245
51              Cabo Verde          7         15   21.22762
52                Cambodia        250         17   57.31159
53                Cameroon        307         14   70.88626
54                  Canada      10431        296   61.94543

In [ ]:
energy.tail(50)

Unnamed: 2 Unnamed: 3 Unnamed: 4  \
193                              Sao Tome and Principe          3         14   
194                                     Saudi Arabia14       7985        264   
195                                            Senegal        154         11   
196                                           Serbia15        618         69   
197                                         Seychelles          9         94   
198                                       Sierra Leone         67         11   
199                                          Singapore       1120        207   
200                          Sint Maarten (Dutch part)         12        327   
201                                           Slovakia        711        131   
202                                           Slovenia        287        139   
203                                    Solomon Islands          6         11   
204                                            Somalia        126         12   
205                                       South Africa       6341        119   
206                                        South Sudan         28          2   
207                                            Spain16       4923        106   
208                                          Sri Lanka        388         19   
209                                 State of Palestine         61         14   
210                                              Sudan        608         16   
211                                           Suriname         34         65   
212                                          Swaziland         49         39   
213                                             Sweden       2044        212   
214                                      Switzerland17       1113        136   
215                               Syrian Arab Republic        542         28   
216                                         Tajikistan        106         13   
217                                           Thailand       5336         79   
218          The former Yugoslav Republic of Macedonia        117         56   
219                                        Timor-Leste          7          6   
220                                               Togo        134         19   
221                                              Tonga          3         28   
222                                Trinidad and Tobago        824        611   
223                                            Tunisia        430         39   
224                                             Turkey       4897         64   
225                                       Turkmenistan       1102        210   
226                           Turks and Caicos Islands          3         85   
227                                             Tuvalu        ...        ...   
228                                             Uganda        452         12   
229                                          Ukraine18       4844        107   
230                               United Arab Emirates       2710        300   
231  United Kingdom of Great Britain and Northern I...       7920        124   
232                        United Republic of Tanzania        994         20   
233                         United States of America20      90838        286   
234                       United States Virgin Islands        ...        ...   
235                                            Uruguay        196         58   
236                                         Uzbekistan       1798         62   
237                                            Vanuatu          3         10   
238                 Venezuela (Bolivarian Republic of)       2871         95   
239                                           Viet Nam       2554         28   
240                          Wallis and Futuna Islands          0         26   
241                                              Yemen        344         13   
242                                         

In [ ]:
energy = energy[9:243]
new_header = ['Country', 'Energy Supply', 'Energy Supply per Capita', 'Renewable Electricity Production']
energy.columns = new_header 
energy

Country Energy Supply  \
54                               Canada         10431   
55                       Cayman Islands             8   
56             Central African Republic            23   
57                                 Chad            77   
58                                Chile          1613   
..                                  ...           ...   
238  Venezuela (Bolivarian Republic of)          2871   
239                            Viet Nam          2554   
240           Wallis and Futuna Islands             0   
241                               Yemen           344   
242                              Zambia           400   

    Energy Supply per Capita Renewable Electricity Production  
54                       296                         61.94543  
55                       131                                0  
56                         5                         85.63536  
57                         6                                0  
58                        92                         28.00657  
..                       ...                              ...  
238                       95                         67.83452  
239                       28                         45.32152  
240                       26                                0  
241                       13                                0  
242                       26                         99.71467  

[189 rows x 4 columns]

In [ ]:
energy.replace('...', np.nan,inplace = True)
energy

Country  Energy Supply  \
54                               Canada        10431.0   
55                       Cayman Islands            8.0   
56             Central African Republic           23.0   
57                                 Chad           77.0   
58                                Chile         1613.0   
..                                  ...            ...   
238  Venezuela (Bolivarian Republic of)         2871.0   
239                            Viet Nam         2554.0   
240           Wallis and Futuna Islands            0.0   
241                               Yemen          344.0   
242                              Zambia          400.0   

     Energy Supply per Capita  Renewable Electricity Production  
54                      296.0                          61.94543  
55                      131.0                           0.00000  
56                        5.0                          85.63536  
57                        6.0                           0.00000  
58                       92.0                          28.00657  
..                        ...                               ...  
238                      95.0                          67.83452  
239                      28.0                          45.32152  
240                      26.0                           0.00000  
241                      13.0                           0.00000  
242                      26.0                          99.71467  

[189 rows x 4 columns]

In [ ]:
energy.Country.replace(r'\s\([^()]*\)', '', regex = True, inplace = True) # s for space before parenthesis
energy.Country.replace(r'\d+', '', regex = True, inplace = True)
energy

Country  Energy Supply  Energy Supply per Capita  \
54                      Canada        10431.0                     296.0   
55              Cayman Islands            8.0                     131.0   
56    Central African Republic           23.0                       5.0   
57                        Chad           77.0                       6.0   
58                       Chile         1613.0                      92.0   
..                         ...            ...                       ...   
238                  Venezuela         2871.0                      95.0   
239                   Viet Nam         2554.0                      28.0   
240  Wallis and Futuna Islands            0.0                      26.0   
241                      Yemen          344.0                      13.0   
242                     Zambia          400.0                      26.0   

     Renewable Electricity Production  
54                           61.94543  
55                            0.00000  
56                           85.63536  
57                            0.00000  
58                           28.00657  
..                                ...  
238                          67.83452  
239                          45.32152  
240                           0.00000  
241                           0.00000  
242                          99.71467  

[189 rows x 4 columns]

In [ ]:
energy['Energy Supply'] *= 1000000
energy

Country  Energy Supply  Energy Supply per Capita  \
54                      Canada   1.043100e+10                     296.0   
55              Cayman Islands   8.000000e+06                     131.0   
56    Central African Republic   2.300000e+07                       5.0   
57                        Chad   7.700000e+07                       6.0   
58                       Chile   1.613000e+09                      92.0   
..                         ...            ...                       ...   
238                  Venezuela   2.871000e+09                      95.0   
239                   Viet Nam   2.554000e+09                      28.0   
240  Wallis and Futuna Islands   0.000000e+00                      26.0   
241                      Yemen   3.440000e+08                      13.0   
242                     Zambia   4.000000e+08                      26.0   

     Renewable Electricity Production  
54                           61.94543  
55                            0.00000  
56                           85.63536  
57                            0.00000  
58                           28.00657  
..                                ...  
238                          67.83452  
239                          45.32152  
240                           0.00000  
241                           0.00000  
242                          99.71467  

[189 rows x 4 columns]

In [ ]:
country_name = {"Republic of Korea": "South Korea", 
                "United States of America": "United States",
                "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
                "China, Hong Kong Special Administrative Region": "Hong Kong"}
energy.Country = energy.Country.replace(country_name)
energy

Country  Energy Supply  Energy Supply per Capita  \
54                      Canada   1.043100e+10                     296.0   
55              Cayman Islands   8.000000e+06                     131.0   
56    Central African Republic   2.300000e+07                       5.0   
57                        Chad   7.700000e+07                       6.0   
58                       Chile   1.613000e+09                      92.0   
..                         ...            ...                       ...   
238                  Venezuela   2.871000e+09                      95.0   
239                   Viet Nam   2.554000e+09                      28.0   
240  Wallis and Futuna Islands   0.000000e+00                      26.0   
241                      Yemen   3.440000e+08                      13.0   
242                     Zambia   4.000000e+08                      26.0   

     Renewable Electricity Production  
54                           61.94543  
55                            0.00000  
56                           85.63536  
57                            0.00000  
58                           28.00657  
..                                ...  
238                          67.83452  
239                          45.32152  
240                           0.00000  
241                           0.00000  
242                          99.71467  

[189 rows x 4 columns]

# 18-04-2022

# 5. Write python program for given an arbitrary number of vectors, build the cartesian product (every combinations of every item).

In [ ]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5])
res = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])
print("Cartesian Product for Two Arrays:")
print(res)

Cartesian Product for Two Arrays:
[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]]


In [ ]:
import numpy as np
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    print("Arrays: \n",arrays)
    
    shape = (len(x) for x in arrays)
    

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
        #print(ix)

    return ix

arr1=[1, 2, 3]
arr2=[4,5]
arr3=[6,7]
arr4=[8,9,0]
res=cartesian((arr1, arr2, arr3,arr4))
print("Cartesian Product for Multiple Arrays: \n", res)


Arrays: 
 [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9, 0])]
Cartesian Product for Multiple Arrays: 
 [[1 4 6 8]
 [1 4 6 9]
 [1 4 6 0]
 [1 4 7 8]
 [1 4 7 9]
 [1 4 7 0]
 [1 5 6 8]
 [1 5 6 9]
 [1 5 6 0]
 [1 5 7 8]
 [1 5 7 9]
 [1 5 7 0]
 [2 4 6 8]
 [2 4 6 9]
 [2 4 6 0]
 [2 4 7 8]
 [2 4 7 9]
 [2 4 7 0]
 [2 5 6 8]
 [2 5 6 9]
 [2 5 6 0]
 [2 5 7 8]
 [2 5 7 9]
 [2 5 7 0]
 [3 4 6 8]
 [3 4 6 9]
 [3 4 6 0]
 [3 4 7 8]
 [3 4 7 9]
 [3 4 7 0]
 [3 5 6 8]
 [3 5 6 9]
 [3 5 6 0]
 [3 5 7 8]
 [3 5 7 9]
 [3 5 7 0]]


# 6. Write python program to get value of x for given linear equations.

In [ ]:
from sympy import symbols, Eq, solve
x, y, z = symbols('x,y,z')
eq1 = Eq((x+y+z), 1)
print("Equation 1: ", eq1)
eq2 = Eq((x-y+2*z), 1)
print("Equation 2: ",eq2)
eq3 = Eq((2*x-y+2*z), 1)
print("Equation 3: ",eq3)
print("\n Values of 3 unknown variable are as follows:")
print(solve((eq1, eq2, eq3), (x, y, z)))

Equation 1:  Eq(x + y + z, 1)
Equation 2:  Eq(x - y + 2*z, 1)
Equation 3:  Eq(2*x - y + 2*z, 1)

 Values of 3 unknown variable are as follows:
{x: 0, y: 1/3, z: 2/3}


# 7. Write python program to find eigen analysis for given matrix.

In [ ]:
import numpy as np
m = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])
print("Printing the Original square array:\n",m)
w, v = np.linalg.eig(m)
print("Printing the Eigen values of the given square array:\n",w)
print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]
Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]
